public class DataType {

/**
 *      Data Types in Java
 *      1 . Primitive Data Types
 *      2 . Non-Primitive Data Types
 *
 */
   
   public static void main(String[] args) {
       // Primitive Data Types
       int myNum = 5;               // Integer (whole number)
       float myFloatNum = 5.99f;   // Floating point number
       char myLetter = 'D';        // Character
       boolean myBool = true;      // Boolean
       String myText = "Hello";    // String

       System.out.println("Integer: " + myNum);
       System.out.println("Float: " + myFloatNum);
       System.out.println("Character: " + myLetter);
       System.out.println("Boolean: " + myBool);
       System.out.println("String: " + myText);
       System.out.println("Integer max: " + Integer.MAX_VALUE);
       System.out.println("Integer min: " + Integer.MIN_VALUE);
       System.out.println("Float max: " + Float.MAX_VALUE);
       System.out.println("Float min: " + Float.MIN_VALUE);
   }




}